import pandas as pd
import streamlit as st


def render_report_history():
    df = pd.DataFrame(
        {
            "Report ID": [
                "rep_001",
                "rep_002",
                "rep_003",
                "rep_004",
                "rep_005",
            ],
            "Report Type": [
                "Executive Summary",
                "Latency Report",
                "Cost Report",
                "Error Report",
                "System Health Report",
            ],
            "Generated By": [
                "Admin",
                "System",
                "Admin",
                "System",
                "Admin",
            ],
            "Format": [
                "PDF",
                "CSV",
                "PDF",
                "Excel",
                "PDF",
            ],
            "Status": [
                "Completed",
                "Completed",
                "Completed",
                "Failed",
                "Completed",
            ],
            "Created": [
                "Today 10:05",
                "Today 09:40",
                "Yesterday 18:22",
                "Yesterday 17:10",
                "May 18 14:45",
            ],
        }
    )

    st.markdown('<div class="table-card">', unsafe_allow_html=True)
    st.subheader("Report History")
    st.dataframe(df, use_container_width=True, hide_index=True)
    st.markdown("</div>", unsafe_allow_html=True)